apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ci-token
  namespace: gitlab-build
  labels:
    app: gitlab-ci-runner
data:
  token: ImlRWmZuZnlpVXhvMi1wenAzNVRKIiANCg==

# b49zvupYzsjY4LcNVzh9
