---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
#    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: jenkins.k8shc
    http:
      paths:
        - path: /
          backend:
            serviceName: jenkins-jenkins
            servicePort: 8080
