---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: artifactory-data-volume
  labels:
    type: local
#  annotations:
#    pv.beta.kubernetes.io/gid: "2000"
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/kubedata/artifactorydata"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-claim
#  annotations:
#    pv.beta.kubernetes.io/gid: "2000"
  namespace: default
  labels:
    component: artifactory-artifactory-master
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
